# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JB-CmcuowpNeJMqdYUapFeAUxzjdLm13
"""



import streamlit as st
import pandas as pd
import datetime
import os

# --- CONFIGURATION ---
st.set_page_config(page_title="General Store Agent", layout="wide")

# Load Inventory
#def load_data():
  #  return pd.read_csv('/content/drive/MyDrive/inventory.csv')
def load_data():
    df = pd.read_csv('inventory.csv')
    df.columns = df.columns.str.strip()  # This removes that hidden space
    return df
# --- APP LOGIC ---
#@inventory = load_data()
return pd.read_csv('inventory.csv')
# Use 'query params' or a sidebar to switch between Customer and Owner view
view = st.sidebar.radio("Go to:", ["Customer Ordering", "Owner Dashboard"])

if view == "Customer Ordering":
    st.header("🛒 Welcome to Our Store")
    st.write("Select items to add to your list:")

    # Initialize a shopping cart in the session
    if 'cart' not in st.session_state:
        st.session_state.cart = []

    # Display items by category
    categories = inventory['category'].unique()
    for cat in categories:
        with st.expander(cat):
            items_in_cat = inventory[inventory['category'] == cat]
            for _, row in items_in_cat.iterrows():
                col1, col2 = st.columns([3, 1])
                col1.write(f"{row['item_name']} - ${row['price']:.2f}")
                if col2.button(f"Add", key=row['item_name']):
                    st.session_state.cart.append({'item': row['item_name'], 'price': row['price']})
                    st.toast(f"Added {row['item_name']}")

    # Order Summary
    if st.session_state.cart:
        st.divider()
        st.subheader("Your Order")
        df_cart = pd.DataFrame(st.session_state.cart)
        st.table(df_cart)
        total = df_cart['price'].sum()
        st.write(f"### Total: ${total:.2f}")

        if st.button("Place Order"):
            # In a real app, you'd save this to a database like SQLite
            # For now, we'll simulate sending it to the owner
            st.success("Order sent! Please wait at the counter.")
            # Clear cart
            st.session_state.cart = []

elif view == "Owner Dashboard":
    st.header("📋 Pending Orders")
    st.write("This screen will refresh as customers place orders.")

    # Placeholder for incoming orders logic
    # In production, you would pull from a 'orders.csv' or database here
    st.info("No new orders right now. Scanning for updates...")

import streamlit as st
import pandas as pd
import os

# 1. Load and Clean Data
def load_data():
    df = pd.read_csv('/content/drive/MyDrive/inventory.csv')
    df.columns = df.columns.str.strip() # Fixes the ' category' space error
    return df

inventory = load_data()

# 2. Setup Order Storage
# This creates a file to store orders if it doesn't exist
if not os.path.exists('orders.csv'):
    pd.DataFrame(columns=['Time', 'Items', 'Total']).to_csv('orders.csv', index=False)

view = st.sidebar.radio("Switch View:", ["Customer: Shop Here", "Owner: Tablet Dashboard"])

if view == "Customer: Shop Here":
    st.header("🛒 General Store Ordering")

    if 'cart' not in st.session_state:
        st.session_state.cart = []

    # Display items with Quantity Selector
    categories = inventory['category'].unique()
    for cat in categories:
        st.subheader(f"--- {cat} ---")
        items_in_cat = inventory[inventory['category'] == cat]

        for _, row in items_in_cat.iterrows():
            col1, col2, col3 = st.columns([2, 1, 1])
            col1.write(row['item_name'])
            col2.write(f"₹{row['price']}")

            # Quantity box
            qty = col3.number_input("Qty", min_value=1, max_value=10, key=f"q_{row['item_name']}")

            if col3.button("Add", key=f"b_{row['item_name']}"):
                st.session_state.cart.append({'item': row['item_name'], 'price': row['price'], 'qty': qty})
                st.toast(f"Added {qty} {row['item_name']}")

    # Cart Summary
    if st.session_state.cart:
        st.divider()
        st.subheader("Your Selection")
        df_cart = pd.DataFrame(st.session_state.cart)
        df_cart['Subtotal'] = df_cart['price'] * df_cart['qty']
        st.table(df_cart[['item', 'qty', 'Subtotal']])

        total_bill = df_cart['Subtotal'].sum()
        st.write(f"## Total Bill: ₹{total_bill}")

        if st.button("CONFIRM ORDER"):
            # Save to orders.csv
            new_order = pd.DataFrame([{
                'Time': pd.Timestamp.now().strftime("%H:%M:%S"),
                'Items': ", ".join([f"{i['qty']}x {i['item']}" for i in st.session_state.cart]),
                'Total': total_bill
            }])
            new_order.to_csv('orders.csv', mode='a', header=False, index=False)

            st.success("Order Sent! Please go to the counter.")
            st.session_state.cart = []

elif view == "Owner: Tablet Dashboard":
    st.header("📋 New Orders from Customers")

    # Refresh button to check for new orders
    if st.button("🔄 Refresh for New Orders"):
        st.rerun()

    # Read the orders file
    if os.path.exists('orders.csv'):
        orders_df = pd.read_csv('orders.csv')

        if not orders_df.empty:
            st.write("Current Pending Orders:")
            # Display orders with the newest at the top
            st.dataframe(orders_df.iloc[::-1], use_container_width=True)

            # --- CLEAR ORDERS FEATURE ---
            st.divider()
            if st.button("🗑️ Clear All Orders"):
                # Overwrite the file with just the headers to reset it
                pd.DataFrame(columns=['Time', 'Items', 'Total']).to_csv('orders.csv', index=False)
                st.success("All orders cleared!")
                st.rerun()
        else:
            st.info("No pending orders. The list is empty.")
    else:
        st.error("Orders file not found. Please place an order first.")
    st.header("📋 New Orders from Customers")

    if st.button("Refresh Orders"):
        st.rerun()

    # Read and show orders
    orders_df = pd.read_csv('orders.csv')
    if not orders_df.empty:
        # Show newest orders first
        st.table(orders_df.iloc[::-1])
    else:
        st.write("No orders yet today.")
